#!/bin/sh
# $Id$
#
# Sending via 
VIA="SENDMAIL"
#VIA="localhost"
VIA_ARGS=""
#VIA_ARGS="some additional flags"
#
# DISTFILES EMAIL
DMAIL="distfiles@pld-linux.org"
#
# CVS LOGIN or fill it by hand :)
LOGIN=`cat CVS/Root | awk -F: '{ print $3; }' | perl -pi -e "s/@.+//"`
#LOGIN="djrzulf"
#
# HOST
HOST=`hostname -f`
#HOST="knycz.net"
#
# functions

usage()
{
	echo "\
Usage: fetchsrc_request file.spec [BRANCH]
"
}

#------------------
# main()
if [ "$#" = 0 ]; then
	usage;
	exit 1
fi
if [ "$2" != "" ]; then
	BRANCH="$2"
else
	BRANCH="HEAD"
fi
SPEC="$1"
if [[ "$SPEC" != *.spec ]]; then
	SPEC="$SPEC.spec"
fi

if [ "$VIA" = "SENDMAIL" ]; then
	echo >&2 "Requesting $SPEC:$BRANCH via sendmail${VIA_ARGS:+ ($VIA_ARGS)}"
	cat <<EOF | /usr/sbin/sendmail -t $VIA_ARGS 
To: $DMAIL
From: $LOGIN <$LOGIN@$HOST>
Subject: fetchsrc_request notify 
X-CVS-Module: SPECS
X-distfiles-request: yes
X-Login: $LOGIN
X-Spec: $SPEC
X-Branch: $BRANCH
X-Flags: force-reply
.
EOF
else
	echo >&2 "Requesting $SPEC:$BRANCH via SMTP ($VIA:25)"
	cat <<EOF | /usr/bin/nc $VIA 25 > /dev/null
EHLO $HOST
MAIL FROM: $LOGIN <$LOGIN@$HOST>
RCPT TO: $DMAIL
DATA
To: $DMAIL
Subject: fetchsrc_request notify
X-CVS-Module: SPECS
X-distfiles-request: yes
X-Login: $LOGIN
X-Spec: $SPEC
X-Branch: $BRANCH
X-Flags: force-reply
.
QUIT
EOF
fi

