#!/bin/sh
# $Id$
#
# Sending via 
#VIA="localhost"
VIA="/usr/sbin/sendmail"
#
# DISTFILES EMAIL
DMAIL="plddist@ep09.kernel.pl"
#
# CVS LOGIN or fill it by hand :)
LOGIN=`cat CVS/Root | awk -F: '{ print $3; }' | perl -pi -e "s/@.+//"`
#LOGIN="djrzulf"
#
# HOST
HOST=`hostname -f`
#
# functions

usage()
{
	echo "\
Usage: fetchsrc_request file.spec [BRANCH]
"
}

#------------------
# main()
if [ "$#" = 0 ]; then
	usage;
	exit 1
fi
if [ "$2" != 0 ]; then
	BRANCH=`cat CVS/Entries | grep $1 | awk -F/ '{print $6;}' | cut -c 2-`
else
	BRANCH="HEAD"
fi

MAIL="To: $DMAIL\nFrom: $LOGIN <$LOGIN@$HOST>\nSubject: cvs to df notify\nX-CVS-Module: SPECS\nX-distfiles-request: yes\nX-Login: $LOGIN\nX-Spec: $1\nX-Branch: $BRANCH\nX-Flags: cvs-notify\n.\n
"

echo $MAIL | $VIA

